name: Basic validation

on:
  push:
    branches:
      - test-ubuntu24
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  call-basic-validation:
    name: Basic validation
    uses: priya-kinthali/reusable-workflows/.github/workflows/basic-validation.yml@test-ubuntu24
    with:
      node-version: '20.x'
