name: Check dist/

on:
  push:
    branches:
      - test-ubuntu24
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  call-check-dist:
    name: Check dist/
    uses: priya-kinthali/reusable-workflows/.github/workflows/check-dist.yml@test-ubuntu24
    with:
      node-version: '20.x'
