name: Licensed

on:
  push:
    branches:
      - test-ubuntu24
  pull_request:
    branches:
      - main

jobs:
  call-licensed:
    name: Licensed
    uses: priya-kinthali/reusable-workflows/.github/workflows/licensed.yml@test-ubuntu24
